### ISSUE TITLE
Quickemu installing non official windows iso ?

### ISSUE THREAD

**Issue by vitoo** [quickemu-project/quickemu#494] opened 2022-06-27 09:41 UTC
Hello,

when i run `quickget windows 10 French` (i tried also english) it look like i got a non official windows iso : 
It ask me a Intellek account at first start, instead of a microsoft account, so i can't logon and use the VM

do you also have this issue ? 

Thanks 

![image](https://user-images.githubusercontent.com/995694/175909888-5d9431d6-49c6-44b1-a90c-b325a7599069.png)

**Comment by Jaymoon85** [comment] 2022-07-03 22:20
For what it's worth, I too am getting the same error by installing Windows 11 English via quickemu-gui.

I also swapped out the downloaded .iso file with one straight from microsoft.com. It still forces an "Intellek" login during setup.

Is this maybe due to the default product key being used? or perhaps a config entry that can be changed somewhere? It doesn't seem to be because of the "Win11_English_x64v1.iso" file at all.

**Comment by borreeero** [comment] 2022-07-04 21:51
I think it is not due to the product key. I also swapped out the iso with a Windows 10 one from Microsoft and used my own product key, just to find out the same "Welcome to Intellek" welcome screen. Maybe there is something in the unattended XML.

**Comment by flexiondotorg** [comment] 2022-07-24 01:49
Duplicate of #312

**Closed by flexiondotorg** 2022-07-24 01:49 UTC
