### ISSUE TITLE
shady windows 10 installation?

### ISSUE THREAD

**Issue by victordiaz** [quickemu-project/quickemu#319] opened 2022-01-14 13:40 UTC
#### Expected behaviour
Have generic windows 10 installer messages

#### Actual behaviour
When installing a windows 10 vm I get the following message in the installer
`MB Solutions INTERNAL!` and asking me to use a MB Solutions Internal e-mail
It looks a bit shady, I'm wondering if that is normal :/

![image](https://user-images.githubusercontent.com/422387/149523946-9352a6bb-5ef9-4161-b365-4e72250fc62d.png)

#### Steps to reproduce the behaviour

`quickget windows 10`
`quickemu --vm windows-10.conf`
Start the installer until you reach a screen as the one attached

**Comment by philclifford** [comment] 2022-01-17 13:07
Not shady. Sadly an ongoing saga of something in the automated installs (ours and Microsoft's) triggering this "helpful" corporate behaviour.  While we're trying to find the root cause and make it go away again there is a workaround mentioned in #312 which should work for you.

**Comment by flexiondotorg** [comment] 2022-02-19 15:33
Duplicate of #312

**Closed by flexiondotorg** 2022-02-19 15:33 UTC
