### ISSUE TITLE
bug: RecoveryImage Macos being removed after downloaded

### ISSUE THREAD

**Issue by xensurve** [quickemu-project/quickemu#1229] opened 2024-05-15 01:50 UTC
Distro : Arch
De : plasma
quickemu : qemu-git 

<pre><code>
quickget macos ventura
</pre></code>

it downloads the RecoveryImage.img but when its finished it deletes it , its removed from the folder all thats left is the opencore.qcow2 and ovmf files

I installed the quickemu-git from arch and it deletes the file,  I installed quickemu-4.9.4 from arch and it does'nt delete the file

latest  pull seems to have a bug that deletes the file after downloaded ,can anyone esle confirm

**Comment by flexiondotorg** [comment] 2024-05-15 10:52
Duplicate of #1124

**Comment by samxu29** [comment] 2024-05-15 18:26
Are there any update on this issue yet?

**Comment by philclifford** [comment] 2024-05-15 18:36
It is fixed in an in-progress feature branch.
I the meantime you can work around with 

``` shell
export QEMU_IMG=$(command -v qemu-img)
quickget macos ventura
```

**Closed** 2024-05-17 22:18 UTC
Labels: duplicate
