### ISSUE TITLE
Windows 11 download fails due to unknown certificate

### ISSUE THREAD

**Issue by reesericci** [quickemu-project/quickemu#427] opened 2022-03-22 20:41 UTC
#### Expected behaviour

Download Windows 11 ISO and create config file

#### Actual behaviour

Quickget fails with error message `ERROR! Failed to download https://tb.rg-adguard.net/dl.php?go= with wget. Try running 'quickget' again.`

#### Steps to reproduce the behaviour

Run `quickget windows 11` in the terminal.
Try to visit the download link in the browser without HTTPS override.

#### Quickemu output

```
Getting Windows 11 URL...
jq: error (at <stdin>:0): Cannot iterate over null (null)
Downloading ...
ERROR! Failed to download https://tb.rg-adguard.net/dl.php?go= with wget. Try running 'quickget' again.
```

#### Linux Distribution & Kernel

Fedora 35 Toolbox running on F35 Silverblue

uname -a output:
`Linux toolbox 5.16.12-200.fc35.x86_64 #1 SMP PREEMPT Wed Mar 2 19:06:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

lsb_release output:
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 35 (Thirty Five)
Release:        35
Codename:       ThirtyFive
```

**Comment by stenwt** [comment] 2022-03-24 21:41
seeing same, also on Fedora 35 

```
$ ./quickget windows 10
Getting Windows 10 URL...
Downloading Windows 10, Version 21H2 (build 19044.1288)...
ERROR! Failed to download https://tb.rg-adguard.net/dl.php?go=35782c91 with wget. Try running 'quickget' again.
$ wget https://tb.rg-adguard.net/dl.php?go=35782c91
--2022-03-24 16:38:37--  https://tb.rg-adguard.net/dl.php?go=35782c91
Resolving tb.rg-adguard.net (tb.rg-adguard.net)... 163.172.251.201, 64:ff9b::a3ac:fbc9
Connecting to tb.rg-adguard.net (tb.rg-adguard.net)|163.172.251.201|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://software.download.prss.microsoft.com/db/Win10_21H2_EnglishInternational_x64.iso?t=3bbed690-2460-45f2-a678-020e468ce659&e=1648206263&h=b28c9530304ac73237072315e40161eca04f85d334ef15b6efad5b3cb763af3f [following]
--2022-03-24 16:38:38--  https://software.download.prss.microsoft.com/db/Win10_21H2_EnglishInternational_x64.iso?t=3bbed690-2460-45f2-a678-020e468ce659&e=1648206263&h=b28c9530304ac73237072315e40161eca04f85d334ef15b6efad5b3cb763af3f
Resolving software.download.prss.microsoft.com (software.download.prss.microsoft.com)... 152.195.19.97, 2606:2800:11f:1cb7:261b:1f9c:2074:3c
Connecting to software.download.prss.microsoft.com (software.download.prss.microsoft.com)|152.195.19.97|:443... connected.
ERROR: The certificate of ‘software.download.prss.microsoft.com’ is not trusted.

```

**Comment by philclifford** [comment] 2022-03-25 00:30
> I'm able to work around it by adding `--no-check-certificate` to the wget command in quickget, but that's not a great solution.

I'm **not** being angry or snarky here, and sincere thanks for the very helpful and clear reports.  I am, however, very concerned that for everyone's safety in these interesting times that security should be at the forefront of everyone's attention at all times, and that you should **ONLY** use `--no-check-certificate` where you have absolute knowledge that it is safe so to do (which for me would be when the certificate not to check was one I had made myself when too lazy to sign it with my own trusted CA ).

It seems  from the above that _either_ Fedora 35 (at least for your environments) needs some help trusting Microsoft Azure TLS Issuing CA 02 or  DigiCert Global Root G2 (maybe an update to the trusted CA Certs or similar) _or_ those naughty youngsters who borrowed some Microsoft source code the other day also left something behind in their software delivery pipeline, which strict TLS might have saved you from except you used the handy `--turn-off-security` flag.  Fortunately, it looks like the former case is the problem here, since using https on ubuntu to get the iso works without issues (and manually inspecting the certificate and CA chain checks out fine), so you probably just need to get your  Fedora 35 CA trust issues sorted (pending CA bundle update maybe ?? ) 

```
gnutls-cli software.download.prss.microsoft.com
Processed 130 CA certificate(s).
Resolving 'software.download.prss.microsoft.com:443'...
Connecting to '152.199.21.175:443'...
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `CN=software.download.prss.microsoft.com,O=Microsoft Corporation,L=Redmond,ST=WA,C=US', issuer `CN=Microsoft Azure TLS Issuing CA 02,O=Microsoft Corporation,C=US', serial 0x3300287ef91c29a2bd9cf4b63a000000287ef9, RSA key 2048 bits, signed using RSA-SHA384, activated `2022-02-01 16:18:23 UTC', expires `2022-07-31 16:18:23 UTC', pin-sha256="9NVU1HcNn9ORJsOLY0IqyVdHgS8rvbgkqhLmGuNBwd4="
	Public Key ID:
		sha1:3afbb422dae492604a4b12fb539d809cf9166b7a
		sha256:f4d554d4770d9fd39126c38b63422ac95747812f2bbdb824aa12e61ae341c1de
	Public Key PIN:
		pin-sha256:9NVU1HcNn9ORJsOLY0IqyVdHgS8rvbgkqhLmGuNBwd4=

- Certificate[1] info:
 - subject `CN=Microsoft Azure TLS Issuing CA 02,O=Microsoft Corporation,C=US', issuer `CN=DigiCert Global Root G2,OU=www.digicert.com,O=DigiCert Inc,C=US', serial 0x0c6ae97cced599838690a00a9ea53214, RSA key 4096 bits, signed using RSA-SHA384, activated `2020-07-29 12:30:00 UTC', expires `2024-06-27 23:59:59 UTC', pin-sha256="zAwfx2iFcQ5vMOCc9vt+MXLdLl08EquNsOWgDF0hOw8="
- Status: The certificate is trusted. 
- Description: (TLS1.3-X.509)-(ECDHE-SECP256R1)-(RSA-PSS-RSAE-SHA256)-(AES-256-GCM)
- Session ID: 81:A8:B8:B9:C4:56:10:9F:B4:F8:DA:65:D6:AD:90:85:D6:E0:50:40:04:01:41:71:93:52:47:E4:3C:58:C5:77
- Options: OCSP status request,
- Handshake was completed
```

**Comment by philclifford** [comment] 2022-03-25 00:38
> Try to visit the download link in the browser without HTTPS override.
Thanks Reese, but I think your issue is with TLS/HTTPS and the trusted CAs in your Fedora 35 and `quickget` ( `wget`) is behaving correctly.

**Comment by reesericci** [comment] 2022-03-25 04:29
> > Try to visit the download link in the browser without HTTPS override.
> 
> Thanks Reese, but I think your issue is with TLS/HTTPS and the trusted CAs in your Fedora 35 and `quickget` ( `wget`) is behaving correctly.

I will take a look tomorrow when I get some time.

**Comment by reesericci** [comment] 2022-03-27 03:37
Fedora just uses the mozilla CA chain, and the cert is not in there. I had to modify quickget to use `--no-check-certficate` which is not good.

**Comment by git14** [comment] 2022-04-27 20:19
Confirmed this is something in Fedora 36 and not an issue with quickemu.

Would like some guidance on how to properly address certs not being trusted.

```
gnutls-cli software.download.prss.microsoft.com
Processed 148 CA certificate(s).
Resolving 'software.download.prss.microsoft.com:443'...
Connecting to '152.195.19.97:443'...
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `CN=software.download.prss.microsoft.com,O=Microsoft Corporation,L=Redmond,ST=WA,C=US', issuer `CN=Microsoft Azure TLS Issuing CA 02,O=Microsoft Corporation,C=US', serial 0x3300287ef91c29a2bd9cf4b63a000000287ef9, RSA key 2048 bits, signed using RSA-SHA384, activated `2022-02-01 16:18:23 UTC', expires `2022-07-31 16:18:23 UTC', pin-sha256="9NVU1HcNn9ORJsOLY0IqyVdHgS8rvbgkqhLmGuNBwd4="
	Public Key ID:
		sha1:3afbb422dae492604a4b12fb539d809cf9166b7a
		sha256:f4d554d4770d9fd39126c38b63422ac95747812f2bbdb824aa12e61ae341c1de
	Public Key PIN:
		pin-sha256:9NVU1HcNn9ORJsOLY0IqyVdHgS8rvbgkqhLmGuNBwd4=

- Certificate[1] info:
 - subject `CN=Microsoft Azure TLS Issuing CA 02,O=Microsoft Corporation,C=US', issuer `CN=DigiCert Global Root G2,OU=www.digicert.com,O=DigiCert Inc,C=US', serial 0x0c6ae97cced599838690a00a9ea53214, RSA key 4096 bits, signed using RSA-SHA384, activated `2020-07-29 12:30:00 UTC', expires `2024-06-27 23:59:59 UTC', pin-sha256="zAwfx2iFcQ5vMOCc9vt+MXLdLl08EquNsOWgDF0hOw8="
- Status: The certificate is NOT trusted. The received OCSP status response is invalid. 
*** PKI verification of server certificate failed...
*** Fatal error: Error in the certificate.
```
and wget
```
wget https://tb.rg-adguard.net/dl.php?go=55a5f243
--2022-04-27 13:18:55--  https://tb.rg-adguard.net/dl.php?go=55a5f243
Resolving tb.rg-adguard.net (tb.rg-adguard.net)... 104.21.80.43, 172.67.174.18, 2606:4700:3037::6815:502b, ...
Connecting to tb.rg-adguard.net (tb.rg-adguard.net)|104.21.80.43|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://software.download.prss.microsoft.com/pr/Win11_EnglishInternational_x64v1.iso?t=3d82f089-14f3-40b4-accf-672652c66f05&e=1651143672&h=dcbf31c0c8d2b633a8e4cea222b204168958ec15f62f0b012fd28944f08ac66b [following]
--2022-04-27 13:18:56--  https://software.download.prss.microsoft.com/pr/Win11_EnglishInternational_x64v1.iso?t=3d82f089-14f3-40b4-accf-672652c66f05&e=1651143672&h=dcbf31c0c8d2b633a8e4cea222b204168958ec15f62f0b012fd28944f08ac66b
Resolving software.download.prss.microsoft.com (software.download.prss.microsoft.com)... 152.195.19.97, 2606:2800:11f:1cb7:261b:1f9c:2074:3c
Connecting to software.download.prss.microsoft.com (software.download.prss.microsoft.com)|152.195.19.97|:443... connected.
ERROR: The certificate of ‘software.download.prss.microsoft.com’ is not trusted.

```

**Comment by Heisenbug2022** [comment] 2022-06-12 11:09
curl --location --remote-name 'https://software.download.prss.microsoft.com/dbazure/Win11_English_x64v1.iso?t=b9b18f60-879c-4574-9d34-ee37176552a8&e=1655115680&h=ff47bae47a23873bcf6e956c06e515920bb33aecef9a1e3f64026d6816795c94'
-L, --location      Follow redirects
-O, --remote-name   Write output to a file named as the remote file
     --remote-name-all Use the remote file name for all URLs

**Comment by Heisenbug2022** [comment] 2022-06-12 11:39
`wget "https://software.download.prss.microsoft.com/dbazure/Win11_English_x64v1.iso?t=b9b18f60-879c-4574-9d34-ee37176552a8&e=1655115680&h=ff47bae47a23873bcf6e956c06e515920bb33aecef9a1e3f64026d6816795c94" -O Win11_English_x64v1.iso`

**Comment by flexiondotorg** [comment] 2022-08-01 08:19
Closing this issue and it is not a Quickemu bug.

**Closed by flexiondotorg** 2022-08-01 08:19 UTC
