### ISSUE TITLE
Bridge networking

### ISSUE THREAD

**Issue by nicolasmol** [quickemu-project/quickemu#470] opened 2022-05-16 00:19 UTC
Hello,
I'd be glad after hours and days of invertigations, to hear from someone who has a recent, arch (manjaro) based, explaination on how configure a network bridge with macOS
Thanks

**Comment by flexiondotorg** [comment] 2022-08-01 08:26
Duplicate of #297

**Closed by flexiondotorg** 2022-08-01 08:26 UTC
Labels: duplicate
