### ISSUE TITLE
how i can disable internet acces of vm?

### ISSUE THREAD

**Issue by osevan** [quickemu-project/quickemu#419] opened 2022-03-07 09:22 UTC
I need only localhost connection.

But when I want internet connection etc....

After restart and editing config

His I can do that?

**Comment by philclifford** [comment] 2022-03-07 12:48
Either use firewall/routing on your host/route to block outbound from the VM or set `-nic none` in the generated <vm>/<vm>.sh (or a copy since that will be re-generated if you run quickemu).

Depends what you want to do/achieve. You might want to look at https://wiki.qemu.org/Documentation/Networking

**Comment by osevan** [comment] 2022-03-07 22:17
Where is generated sh located?

**Comment by flexiondotorg** [comment] 2022-08-18 10:05
Kind of a duplicate of #478. Configuring a VM to have no network seems reasonable to me.

**Closed by flexiondotorg** 2022-08-18 10:05 UTC
