### ISSUE TITLE
android x86 64 screen issue

### ISSUE THREAD

**Issue by bheeshmpita** [quickemu-project/quickemu#607] opened 2022-12-28 07:57 UTC
#### Expected behaviour
vm to run without any error

(i am not an advanced linux user with minimum knowledge of technicalities of programs. so my responses may not be apt) 

#### Actual behaviour
on starting vm error generated "Guest has not initiated the display (yet)" and on selecting the live mode, error reported is "display output is not active"
while the former error occurs for linux vm too but it starts without any problems, hence no latter error

but i was able to to run android vm by this command `quickemu --vm android-9.0-x86_64.conf --screen 0` without any status bar and other features which are available near title bar of vm such as usb redirect.

#### Steps to reproduce the behaviour
1. start quickemu gui
2. manage existing machines
3. start by clicking play button besides android-9.0-x86_64

#### Quickemu output
on running android live mode
```
detecting android-x86...found at /dev/sr0
console:/ 
```

and then nothing happens

#### Linux Distribution & Kernel
OS: Linux Mint 21 x86_64
Kernel: 5.15.0-56-generic

**Comment by flexiondotorg** [comment] 2024-04-16 19:02
I can't reproduce this issue, it looks like this has been fixed in recent versions of Quickemu.

**Closed by flexiondotorg** 2024-04-16 19:02 UTC
