### ISSUE TITLE
mac os vm doesnt work

### ISSUE THREAD

**Issue by Jusxern** [quickemu-project/quickemu#1221] opened 2024-05-14 13:25 UTC
# Expected behavior

Run Mac OS vm on Arch linux

## Actual behavior

Errors immediately after startup

# Steps to reproduce the behavior

Outline the steps to reproduce the issue you've encountered.

# Additional context

I also found the same issue, but nothing worked for me. 

## Quickemu output

Run `quickemu` or `quickemu` and include the output of the failure below:

<details>
  <summary>Quickemu output</summary>

  ```text
Quickemu 4.9.4 using /usr/bin/qemu-system-x86_64 v9.0.0
 - Host:     Arch Linux running Linux 6.8 (archlinux)
 - CPU:      11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (macOS), OVMF (OVMF_CODE.fd), SecureBoot (off).
 - Disk:     macos-sonoma/disk.qcow2 (96G)
             Looks unused, booting from macos-sonoma/RecoveryImage.img
 - Recovery: macos-sonoma/RecoveryImage.img
 - Display:  SDL, qxl-vga, GL (on), VirGL (off)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - 9P:       On guest: sudo mount_9p Public-xern
 - 9P:       On host:  chmod 777 /home/xern/Shared
             Required for macOS integration 👆
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "macos-sonoma/macos-sonoma-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:macos-sonoma/macos-sonoma-monitor.socket
 - Serial:   On host:  nc -U "macos-sonoma/macos-sonoma-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:macos-sonoma/macos-sonoma-serial.socket
cat: macos-sonoma/macos-sonoma.pid: No such file or directory
 - Process:  Starting macos-sonoma.conf as macos-sonoma ()

  ```
</details>

**Comment by mortbauer** [comment] 2024-05-14 14:28
Have the same issue on archlinux with a windows vm. Probably it is because of qemu v9.0.0 on archlinux?

**Comment by mortbauer** [comment] 2024-05-14 14:34
Actually it works for me more or less when I downgrade quickemu to 4.9.2, with this version I get the error `qemu-system-x86_64: -no-hpet: invalid option`, after manually deleting the line with that option from in my case `windows-11/windows-11-22H2.sh` file  and then running that bash script I get a working vm again.

**Comment by flexiondotorg** [comment] 2024-05-14 14:42
Duplicate of https://github.com/quickemu-project/quickemu/issues/1214

The `-no-hpet` issue is fixed in 4.9.4.

**Closed by flexiondotorg** 2024-05-14 14:42 UTC
Labels: duplicate

**Comment by mortbauer** [comment] 2024-05-14 17:49
I know, but in 4.9.4 it simply doesn't work at all as shown in the logs `cat: macos-sonoma/macos-sonoma.pid: No such file or directory`

**Comment by AbdullahPrime** [comment] 2024-05-27 10:35
> I know, but in 4.9.4 it simply doesn't work at all as shown in the logs `cat: macos-sonoma/macos-sonoma.pid: No such file or directory`

This is EXACTLY the issue ....

**Comment by mortbauer** [comment] 2024-05-27 13:17
might actually be correlated with the kernel version, because I was using the lts kernel when the issue happened. 
Right now I'm using `6.9.1-arch1-2` and tried quickemu 4.9.4 again and everything  works perfectly now.
