### ISSUE TITLE
Windows $LANGS and windows-server

### ISSUE THREAD

**Issue by TuxVinyards** [quickemu-project/quickemu#1113] opened 2024-04-25 06:20 UTC
### What kind of interface behaviour do we want here?  

Do we go for English unless specified or should we throw an error and ask for input?   Should 'Default' be an option choice?

And what method do we use to display all the language option sets?

### Few glitches that I spotted:

``` 
./quickget windows
ERROR! You must specify a release.
 - Releases: 11 10-ltsc 10 8
 - Languages: Arabic Brazilian Portuguese Bulgarian Chinese (Simplified) Chinese (Traditional) Croatian Czech Danish Dutch English (United States) English International Estonian Finnish French French Canadian German Greek Hebrew Hungarian Italian Japanese Korean Latvian Lithuanian Norwegian Polish Portuguese Romanian Russian Serbian Latin Slovak Slovenian Spanish Spanish (Mexico) Swedish Thai Turkish Ukrainian

``` 
Shows  the `function languages_windows()`   `else` option only  ie 10 and 11  whilst Version 8 and 10-ltsc never get shown.

And  are we missing an  "ERROR! You must specify a language."  message trap, like you would normally get, as in:

```
./quickget -u  fedora 39
ERROR! You must specify an edition.
 - Editions: Workstation Budgie Cinnamon i3 KDE LXDE LXQt Mate Xfce Silverblue Sericea Kinoite Sway Server Onyx
 
 ```
Unless a language is given, it just starts downloading English International.  

ALSO:

```
 ./quickget -u  windows 10 French
 - Microsoft servers gave us no download link to our request for an automated download. Please manually download this ISO in a web browser: https://www.microsoft.com/en-us/software-download/windows10ISO
Downloading VirtIO drivers...
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.240-1/virtio-win-0.1.240.iso

``` 
Fails for "French"  but works for "French Canadian"   

Also on fail, a message displays that VirtIO is downloading ....   Actually doesn't though.

```
./quickget -u  windows-server 2022
Downloading Windows Server 2022 (English International): https://software-static.download.prss.microsoft.com/sg/download/888969d5-f34g-4e03-ac9d-1f9786c66749/SERVER_EVAL_x64FRE_en-us.iso
###############                                        

```
Fails on option -u  and starts downloading instead.

EDIT:

These space separated lists are also very difficult to grep.  Or even to human process. 

For example  Brazilian Portuguese  looks like two separate langauges here:   

`  - Languages: Arabic Brazilian Portuguese Bulgarian Chinese `  

It's only when we get to see ` Norwegian Polish Portuguese Romanian Russian `  that it makes sense.

_What about introducing separators?_

eg:

```
 - Releases: 11 10-ltsc 10 8
 - Languages: Arabic : Brazilian Portuguese : Bulgarian : Chinese (Simplified) : Chinese (Traditional) : Croatian : Czech : Danish : Dutch : English (United States) : English International : Estonian : Finnish : French : French Canadian : German : etc ....  Greek Hebrew Hungarian Italian Japanese Korean Latvian Lithuanian Norwegian Polish Portuguese Romanian Russian Serbian Latin Slovak Slovenian Spanish Spanish (Mexico) Swedish Thai Turkish Ukrainian

```

**Comment by lj3954** [comment] 2024-04-25 16:22
Failing --url is a bug, I'll look into it later. I believe I noticed the same a couple days ago. I'll look into it later. Separating languages is something I considered, or possibly replacing spaces with hyphens and removing parens, but I never decided upon a solution for this. It should certainly be looked into. 

Not requiring a language is intended behavior. I assume most people using quickget would want an English ISO, languages are just there as an option for those who want them. Quickget also doesn't support listing different editions (or languages) per release, so it does indeed list only the editions for windows 10 and 11 unless you use an invalid language with other versions. I think this is a very minor issue, since as before, I believe the majority of people will use quickget to download windows 10 or 11, rather than 8 (which is EOL anyways, nobody should need that) or 10-ltsc.

**Comment by lj3954** [comment] 2024-04-25 20:10
> Agree with first paragraph.
> 
> Second, why both with other languages, people should all learn to speak English ... Hmm

I absolutely didn't say everyone should have to speak English. I'm not sure why I would've added languages in that case. English is just the default, since the majority of people using quickemu almost certainly speak it. Most other operating systems in quickget also are in English by default, and currently, translations are not available in quickget or quickemu. I think it's much more convenient to just be able to type 'quickget windows 11', for example, than to have to specify a language. 

That does bring up a decent idea, though, the default should probably be changed to use the system locale. I maintain my opposition to making the selection of a language a requirement. When it comes to your project, I would highly recommend using list_csv instead of what you're currently doing. After my PR https://github.com/quickemu-project/quickemu/pull/1089 is merged, list_csv should take closer to 5 seconds to run, and you can parse all OS/Release/Edition options from there, without having to perform a bunch of string manipulation which doesn't work very reliably and breaks on every other quickget update.

**Comment by TuxVinyards** [comment] 2024-04-25 20:26
I am sure that we will get this sorted 👍

**Comment by TuxVinyards** [comment] 2024-04-26 07:14
Something else that we will have to take into account soon. 

Came up in my news feed this morning. In Italian ... 

![Screenshot_2024-04-26-09-09-46-225_com.android.chrome-edit.jpg](https://github.com/quickemu-project/quickemu/assets/3956806/4aa13924-a390-4c42-8e3b-2ec65b590c61)

❤️

**Comment by flexiondotorg** [comment] 2024-04-30 11:24
> That does bring up a decent idea, though, the default should probably be changed to use the system locale. 

Good idea.

> I maintain my opposition to making the selection of a language a requirement.

I agree.

**Closed by flexiondotorg** 2024-04-30 11:24 UTC
