### ISSUE TITLE
bug: VM fail to boot outside of directory

### ISSUE THREAD

**Issue by Fuckingnameless** [quickemu-project/quickemu#874] opened 2023-12-15 03:53 UTC
#### Expected behaviour

i downloaded the win10 distro through quickget, it complained there was no disk and suggested running the machine to create the disk, i ran it "sudo quickemu --vm /root/VMQs/windows-10.conf" but it throws this error:

#### Actual behaviour

cp: cannot create regular file 'windows-10/OVMF_VARS.fd': No such file or directory
 - EFI:      ERROR! windows-10/OVMF_VARS.fd is not a regular file or not writeable.
             Deleting windows-10/OVMF_VARS.fd. Please re-run quickemu.

quickgui does not load either just a blank screen

#### Steps to reproduce the behaviour

sudo quickemu --vm /root/VMQs/windows-10.conf

#### Quickemu output

cp: cannot create regular file 'windows-10/OVMF_VARS.fd': No such file or directory
 - EFI:      ERROR! windows-10/OVMF_VARS.fd is not a regular file or not writeable.
             Deleting windows-10/OVMF_VARS.fd. Please re-run quickemu.

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
uname -a
```
^^ this does nothing
default kernel on latest LTS Ubuntu 22.04

**Comment by lj3954** [comment] 2023-12-15 05:30
I can replicate this. Launching a VM from a different directory than the one you're currently in does not work under any circumstances. This is caused by the VMDIR variables (along with several other variables, such as the image files which use the incomplete paths in the config file) disregarding the directory of the config file and instead using your current directory.

**Comment by lj3954** [comment] 2023-12-15 06:12
This fix creates another issue, VMs in a path with any space will not launch. Don't merge that, more work needs to be done.

**Comment by Fuckingnameless** [comment] 2023-12-15 11:36
it won´t run when i launch it from the VM folder either:

qemu-system-x86_64: -drive media=cdrom,index=0,file=windows-10/windows-10.iso: Could not open 'windows-10/windows-10.iso': No such file or directory
cat: windows-10/windows-10.pid: No such file or directory
 - Process:  Starting windows-10.conf as windows-10 ()
 - Sending:  sendkey ret
2023/12/15 08:31:51 socat[12048] E connect(5, AF=1 "windows-10/windows-10-monitor.socket", 38): Connection refused

also i don´t get why it is asking to connect to spice instead of just opening a screen like a normal VM program would do

**Comment by philclifford** [comment] 2023-12-16 13:36
Don't use sudo.  Run quickget, quickemu and quickgui as an unprivileged user. If necessary give that user the minimum privileges needed to run qemu VMs (there may be a group or role for this). The config,   directory and any files will be where you are when you run quickget. That is where you should be to run quickemu. quickgui will likewise find and present all the VM configs beneath its current directory, which can be selected on the main view.

**Comment by Fuckingnameless** [comment] 2023-12-18 15:27
> It's unable to find your ISO file, meaning you're either in the wrong directory, the ISO doesn't exist or is named incorrectly, or you don't have superuser privileges which are necessary to access the /root directory. Paste the output of `ls windows-10` while you're in the directory you created the VM in.

none of that was the issue i ended uninstalling this piece of crap, there are articles advertising it comes with windows installation option built in which is not true

**Comment by lj3954** [comment] 2023-12-19 01:25
It definitely does automatically install windows 10 and 11. All you need to do is press "next" on the first installation dialog, and everything else is handled for you by the unattended windows XML. The reason you were having issues is because you somehow broke it by opening a VM from a different directory or by installing it in the /root directory (which you should never use for storing your own files).

**Comment by flexiondotorg** [comment] 2024-04-16 19:05
Fixed via https://github.com/quickemu-project/quickemu/pull/1006

**Closed by flexiondotorg** 2024-04-16 19:05 UTC
Labels: bug
