### ISSUE TITLE
error running windows vm since quickemu 4.3

### ISSUE THREAD

**Issue by donnykurnia** [quickemu-project/quickemu#594] opened 2022-11-27 01:09 UTC
#### Expected behaviour

Windows VM can be run.

#### Actual behaviour

windows VM failed to run with MSR error.

#### Steps to reproduce the behaviour

Running any existing windows VM or create new one will produce the errors below.

#### Quickemu output

```
qemu-system-x86_64: error: failed to set MSR 0x48d to 0x7f00000016
qemu-system-x86_64: ../../target/i386/kvm/kvm.c:2753: kvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.
```

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
$ lsb_release --all
No LSB modules are available.
Distributor ID: Linuxmint
Description:    Linux Mint 20.3
Release:        20.3
Codename:       una

$ uname -a
Linux T480s 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ qemu-system-x86_64 --version
QEMU emulator version 6.0.0 (Debian 1:6.0+dfsg-2expubuntu1~focal1.0)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers

$ qemu-system-x86_64 -enable-kvm -cpu host,kvm=on,hv_passthrough
qemu-system-x86_64: error: failed to set MSR 0x48d to 0x7f00000016
qemu-system-x86_64: ../../target/i386/kvm/kvm.c:2753: kvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.
[1]    1392871 abort (core dumped)  qemu-system-x86_64 -enable-kvm -cpu host,kvm=on,hv_passthrough

```

Related commit:
https://github.com/quickemu-project/quickemu/commit/ddbbc23d3447ceb1503bf549a000e0cace5cc723

Quickfix for now:

Changing `hv_passthrough` back to the previous flags works. 
Either edit and run the modified sh file for the VM or edit `/usr/bin/quickemu` and change `hv_passthrough` back into `hv_frequencies,kvm_pv_unhalt,hv_reenlightenment,hv_relaxed,hv_spinlocks=8191,hv_stimer,hv_synic,hv_time,hv_vapic,hv_vendor_id=1234567890ab,hv_vpindex`

Additional info:
I run manjaro VM, and in it it have qemu version 7. I could run the `qemu-system-x86_64 -enable-kvm -cpu host,kvm=on,hv_passthrough` command in it without error. So I guess that the `hv_passthrough` not yet available in qemu below version 7.

**Comment by flexiondotorg** [comment] 2022-12-11 20:32
Duplicate of #572

**Closed by flexiondotorg** 2022-12-11 20:32 UTC

**Comment by donnykurnia** [comment] 2022-12-12 05:27
Hi @flexiondotorg 
The issue that I have in my linux mint is caused by the usage of `hv_passthrough` and it's still not working in the quickemu 4.5

```
quickemu --vm windows-10.conf
Quickemu 4.5 using /usr/bin/qemu-system-x86_64 v6.0.0
 - Host:     Linux Mint 20.3 running Linux 5.4 (T480s)
 - CPU:      Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Windows), OVMF (/usr/share/OVMF/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     windows-10/disk.qcow2 (64G)
 - CD-ROM:   /vm/isos/virtio-win-0.1.225-2.iso
 - Display:  SPICE, qxl-vga, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "windows-10" --port 5930 --spice-shared-dir /home/donny/Public
 - WebDAV:   On guest: dav://localhost:9843/
 - smbd:     On guest: smb://10.0.2.4/qemu
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "windows-10/windows-10-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-monitor.socket
 - Serial:   On host:  nc -U "windows-10/windows-10-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:windows-10/windows-10-serial.socket
qemu-system-x86_64: error: failed to set MSR 0x48d to 0x7f00000016
qemu-system-x86_64: ../../target/i386/kvm/kvm.c:2753: kvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.
 - Process:  Starting windows-10.conf as windows-10 (1002233)
 - Viewer:   spicy --title "windows-10" --port "5930" --spice-shared-dir "/home/donny/Public" "" >/dev/null 2>&1 &
```
```
qemu-system-x86_64 --version
QEMU emulator version 6.0.0 (Debian 1:6.0+dfsg-2expubuntu1~focal1.0)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
```
```
qemu-system-x86_64 -enable-kvm -cpu host,kvm=on,hv_passthrough
qemu-system-x86_64: error: failed to set MSR 0x48d to 0x7f00000016
qemu-system-x86_64: ../../target/i386/kvm/kvm.c:2753: kvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.
[1]    1003001 abort (core dumped)  qemu-system-x86_64 -enable-kvm -cpu host,kvm=on,hv_passthrough
```
While this is working
```
qemu-system-x86_64 -enable-kvm -cpu host,kvm=on,hv_frequencies,kvm_pv_unhalt,hv_reenlightenment,hv_relaxed,hv_spinlocks=8191,hv_stimer,hv_synic,hv_time,hv_vapic,hv_vendor_id=1234567890ab,hv_vpindex
```
