### ISSUE TITLE
Black screen after login with Xubuntu 22.04

### ISSUE THREAD

**Issue by ali1234** [quickemu-project/quickemu#454] opened 2022-05-03 22:19 UTC
#### Expected behaviour

After installing Xubuntu and logging in, the Xubuntu desktop should be displayed.

#### Actual behaviour

After logging in, the screen is black.

#### Steps to reproduce the behaviour

Run the following commands:

```
quickget xubuntu 22.04
quickemu --vm xubuntu-22.04.conf
```
Follow the installation steps, reboot the VM, and log in at the login screen.

#### Quickemu output

```
al@al-desktop:~/quickemu$ quickemu --vm xubuntu-22.04.conf 
Quickemu 4.0 using /usr/bin/qemu-system-x86_64 v6.2.0
 - Host:     Ubuntu 22.04.1 LTS running Linux 5.15 (al-desktop)
 - CPU:      Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
 - CPU VM:   1 Socket(s), 2 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Linux), OVMF (/usr/share/OVMF/OVMF_CODE_4M.fd), SecureBoot (off).
 - Disk:     xubuntu-22.04/disk.qcow2 (16G)
 - Display:  SDL, virtio-vga, GL (on), VirGL (on)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "xubuntu-22.04" --port 5930 --spice-shared-dir /home/al/Public
 - WebDAV:   On guest: dav://localhost:9843/
 - 9P:       On guest: sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600 Public-al ~/Public
 - Monitor:  On host:  nc -U "xubuntu-22.04/xubuntu-22.04-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:xubuntu-22.04/xubuntu-22.04-monitor.socket
 - Serial:   On host:  nc -U "xubuntu-22.04/xubuntu-22.04-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:xubuntu-22.04/xubuntu-22.04-serial.socket
 - Process:  Starting xubuntu-22.04.conf as xubuntu-22.04 (235262)
---
al@al-desktop:~/quickemu$ gl_version 46 - core profile enabled
GLSL feature level 460
```

#### Linux Distribution & Kernel

```
al@al-desktop:~$ bash
al@al-desktop:~$ lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
al@al-desktop:~$ uname -a
Linux al-desktop 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by flexiondotorg** [comment] 2022-07-24 00:38
I can't reproduce this.

**Comment by ali1234** [comment] 2022-08-13 15:31
Tested on Xubuntu 22.04 host - same result.

**Comment by flexiondotorg** [comment] 2022-08-19 21:30
Please update the first post with the issue template completed.

**Comment by ali1234** [comment] 2022-08-19 21:49
Done.

**Comment by flexiondotorg** [comment] 2022-08-19 22:42
Thanks! I've reproduced this on AMD and NVIDIA graphics using QEMU 6.2.0 and QEMU 7.0. The QEMU `sdl` (default) and `gtk` displays exhibit the black screen issue you describe, but `spice` and `spice-app` work correctly (using git master).

There are three workarounds:

  - Add `--display spice` or `--display spice-app` (if you have `virt-viewer` 8.0 or newer installed) to the command line when launching the VM, this *might* require git master of `quickemu`.
  - Add `gl=off` to the VM configuration file.
  - Start the Xubuntu VM using one of the methods above and change the xfwm4's `vblank_mode` to `xpresent`:
    - `xfconf-query -c xfwm4 -p /general/vblank_mode -s xpresent`

This is not a bug with Quickemu, given it is just a wrapper for QEMU. I observe the same issue with Manjaro XFCE and the same workarounds apply.

I'm going to close this issue as it looks like this is a known incompatibility with the `xfwm4` compositor and VirGL when xfwm4's `vblank_mode` uses `glx`, which is the default.

  - https://bugs.launchpad.net/ubuntu/+source/lightdm/+bug/1868780/comments/14
  - https://gitlab.com/postmarketOS/pmaports/-/issues/368

**Closed by flexiondotorg** 2022-08-19 22:42 UTC
Labels: question

**Comment by ali1234** [comment] 2022-08-19 23:12
What did you do differently that allowed you to reproduce it when you couldn't before?

**Comment by flexiondotorg** [comment] 2022-08-20 09:24
I usually launch my VMs via Quickgui which uses SPICE by default.
