### ISSUE TITLE
Windows 10 has SAP customization 

### ISSUE THREAD

**Issue by hjolli** [quickemu-project/quickemu#265] opened 2021-12-06 09:43 UTC
#### Expected behaviour

Install windows 10 and be able to create a user
#### Actual behaviour

After installation the vm has SAP customization and I am unable to create a user

#### Steps to reproduce the behaviour

./quickget windows 10
./quickemu --vm windows-10.conf

#### Quickemu output

Run `quickemu` or `quickget` and paste the output here.

#### Linux Distribution & Kernel

Linux stilgar 5.15.5-200.fc35.x86_64 #1 SMP Fri Nov 26 00:46:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 35 (Thirty Five)
Release:	35
Codename:	ThirtyFive

**Comment by hjolli** [comment] 2021-12-06 09:51
Here is a screen sho
![Screenshot from 2021-12-06 10-36-51](https://user-images.githubusercontent.com/1314568/144825052-539d5278-7595-40b0-b800-704bdb55291f.png)
t

**Comment by daPhipz** [comment] 2021-12-06 10:15
Hello hjolli!
This is a known issue (see #115 for further info) and seemed fixed for some time, but came back over the last days.
If you are able to prvide further info, please comment at #115 or join the WimpysWorld Discord server and comment there.
Thank you!

Duplicate of #115.

**Comment by flexiondotorg** [comment] 2021-12-06 11:47
Fixed via https://github.com/quickemu-project/quickemu/commit/f8aee430ecce2ab687c057842382460e20166e60

**Closed by flexiondotorg** 2021-12-06 11:47 UTC
