### ISSUE TITLE
bug: Silverblue VM not starting

### ISSUE THREAD

**Issue by dajix350** [quickemu-project/quickemu#1257] opened 2024-05-28 13:40 UTC
# Expected behavior

A Fedora 40 Silverblue VM to start after being created with quickget

## Actual behavior

UEFI boot error screenshotted below
![Screenshot_20240528_233219](https://github.com/quickemu-project/quickemu/assets/74509183/0eee1101-dcaf-45fc-a802-3dbde00a778b)

# Steps to reproduce the behavior

```
quickget fedora 40 Silverblue
quickemu --vm fedora-40-Silverblue.conf
```

# Additional context

## Quickemu output

Run `quickemu` or `quickemu` and include the output of the failure below:

<details>
  <summary>Quickemu output</summary>

  ```text
~/Documents/Boxes ~/Documents/Boxes
Quickemu 4.9.4 using /usr/bin/qemu-system-x86_64 v9.0.0
 - Host:     Arch Linux running Linux 6.9 (archbtw)
 - CPU:      AMD Ryzen 5 3500X 6-Core Processor
 - CPU VM:   1 Socket(s), 2 Core(s), 1 Thread(s), 8G RAM
 - BOOT:     EFI (Linux), OVMF (/usr/share/edk2-ovmf/x64/OVMF_CODE.fd), SecureBoot (off).
 - Disk:     fedora-40-Silverblue/disk.qcow2 (16G)
             Just created, booting from fedora-40-Silverblue/Fedora-Silverblue-40.1.14.ociarchive
 - Boot ISO: fedora-40-Silverblue/Fedora-Silverblue-40.1.14.ociarchive
 - Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - 9P:       On guest: sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600 Public-dajix ~/Public
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "fedora-40-Silverblue/fedora-40-Silverblue-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:fedora-40-Silverblue/fedora-40-Silverblue-monitor.socket
 - Serial:   On host:  nc -U "fedora-40-Silverblue/fedora-40-Silverblue-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:fedora-40-Silverblue/fedora-40-Silverblue-serial.socket
 - Process:  Starting fedora-40-Silverblue.conf as fedora-40-Silverblue (70012)
  ```
</details>

## System Information

**Run `quickreport` and include the output here**; if you can't run `quickreport`,
please provide the output of the following:

```bash
clear && \
echo -e "Ver:\t$(quickemu --version)" && \
echo -e "Distro:\t$(grep PRETTY_NAME /etc/os-release | cut -d'"' -f2)" && \
echo -e "Kernel:\t$(uname -s -r -m)" && \
echo -e "Memory:\t$(free --si -h | awk '/Mem:/{print $2}')" && \
lspci | grep -i vga | cut -d':' -f3 && echo && \
curl --version && echo && \
qemu-system-"$(uname -m)" -version | head -1 && \
qemu-system-"$(uname -m)" -cpu help && echo && \
lscpu | tee quickreport.txt
```

<details>
  <summary>Quickreport output</summary>
  NOTE: This was too long to include in the issue without going over the comment size limit
  
[quickreport.txt](https://github.com/quickemu-project/quickemu/files/15470553/quickreport.txt)

</details>

**Comment by lj3954** [comment] 2024-05-29 22:59
I believe a similar bug has been reported before. Quickget incorrectly downloads whatever the top entry in fedora's [releases.json](https://fedoraproject.org/releases.json) while disregarding the format of the file.

**Comment by flexiondotorg** [comment] 2024-06-24 08:59
Duplicate of https://github.com/quickemu-project/quickemu/issues/1245

**Comment by OhMyMndy** [comment] 2024-07-03 13:57
I have the same issue with **Fedora** **Silverblue**, in the [releases.json](https://fedoraproject.org/releases.json) there are multiple **Silverblue** items, but only one is an _.iso_, the other is an `.ociarchive`. The `.ociarchive` also doesn't have an `sha256`.

See this excerpt of the [releases.json](https://fedoraproject.org/releases.json) for **Silverblue**

```
{
"version": "40",
"arch": "x86_64",
"link": "https://download.fedoraproject.org/pub/fedora/linux/releases/40/Silverblue/x86_64/images/Fedora-Silverblue-40.1.14.ociarchive",
"variant": "Silverblue",
"subvariant": "Silverblue"
},
{
"version": "40",
"arch": "x86_64",
"link": "https://download.fedoraproject.org/pub/fedora/linux/releases/40/Silverblue/x86_64/iso/Fedora-Silverblue-ostree-x86_64-40-1.14.iso",
"variant": "Silverblue",
"subvariant": "Silverblue",
"sha256": "8f49c9880cf0eb24e0461498d27d3d5134f056975c478f7d0febb1b9e5d1edbb",
"size": "3582482432"
},
```

Mo

**Closed** 2024-07-03 16:12 UTC
Labels: bug, help wanted
