### ISSUE TITLE
Trouble with Intel Graphics with macos catalina

### ISSUE THREAD

**Issue by sam5558** [quickemu-project/quickemu#258] opened 2021-12-01 08:10 UTC
Hello,

Thanks for this project, love it ! 

#### Expected behaviour

I believe the VM should be able to detect my intel graphics and display it in the .. with something more than 5MB.

#### Actual behaviour

macOS catalina seems to ignore this, only using a generic monitor with 5MB...

![Screenshot_20211201_090615](https://user-images.githubusercontent.com/26897744/144195795-803357ee-b206-4f9e-972b-c24741a5e6c1.png)

![Screenshot_20211201_090702](https://user-images.githubusercontent.com/26897744/144195877-4e51b2e0-d7e6-4d6f-82c0-3cec18aa3dd0.png)

#### Steps to reproduce the behaviour

Nothing but installing the VM.

#### Quickemu output
```bash
 ~/quickgui ▓▒░ quickemu --vm macos-catalina.conf                              
                         
Quickemu 2.3.2 using /usr/bin/qemu-system-x86_64 v6.1.0
 - Host:     "Manjaro Linux" running Linux 5.10
 - CPU:      Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
 - CPU VM:   1 Socket(s), 1 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (macOS), OVMF (OVMF_CODE.fd), SecureBoot (off).
 - Disk:     macos-catalina/disk.qcow2 (96G)
 - MSR:      WARNING! Ignoring unhandled Model-Specific Registers is disabled.

             echo 1 | sudo tee /sys/module/kvm/parameters/ignore_msrs

             If you are unable to run macOS or Windows VMs then run the above 👆
             This will enable ignoring of unhandled MSRs until you reboot the host.
             You can make this change permenant by running: 'quickemu --ignore-msrs-always'
 - Display:  SDL, VGA, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "macos-catalina" --port 5930
 - WebDAV:   On guest: build spice-webdavd (https://gitlab.gnome.org/GNOME/phodav/-/merge_requests/24)
 - WebDAV:   On guest: Finder -> Connect to Server -> http://localhost:9843/
 - 9P:       On guest: sudo mount_9p Public-***
 - 9P:       On host:  chmod 777 /home/***/Public
             Required for macOS integration 👆
 - smbd:     On guest: smb://10.0.2.4/qemu
 - Process:  Starting macos-catalina.conf as macos-catalina (4042)
```

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.2.0
Codename:	Qonos


Linux ***-**** 5.10.79-1-MANJARO #1 SMP PREEMPT Fri Nov 12 20:26:09 UTC 2021 x86_64 GNU/Linux

```

**Comment by flexiondotorg** [comment] 2021-12-03 10:22
Duplicate of #211

**Closed by flexiondotorg** 2021-12-03 10:22 UTC
