### ISSUE TITLE
macos-monterey can't login to app store

### ISSUE THREAD

**Issue by sowinski** [quickemu-project/quickemu#486] opened 2022-06-09 15:26 UTC
#### Expected behaviour

Login to App Store without problems

#### Actual behaviour

Can't login

#### Steps to reproduce the behaviour

Download newest version of quickemu on Linux Mint 20.3 and install macos-monterey

#### Quickemu output

I think this is not related to quickemu output

#### Linux Distribution & Kernel

Run the following and paste the output.

```
lsb_release --all
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.3
Release:	20.3
Codename:	una
uname -a
Linux ps-desktop 5.13.0-44-generic #49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

My final goal is to download Xcode and to run an ios simulator and debug a safari bug. If I download XCode manually I can not connect with Safari to the iOS Simulator. I guess I have to download XCode from the AppStore and login to my account?

**Comment by flexiondotorg** [comment] 2022-07-24 00:36
Duplicate of #474

**Closed by flexiondotorg** 2022-07-24 00:36 UTC
Labels: duplicate
