### ISSUE TITLE
Windows 11 host requires an organization login

### ISSUE THREAD

**Issue by someone2639** [quickemu-project/quickemu#312] opened 2022-01-08 06:28 UTC
#### Expected behaviour
Windows 11 should install a home edition to the virtual disk and allow me to sign in with my personal Microsoft account.

#### Actual behaviour

The guest requires a work/school login from MBSolutions, which I am in no way affiliated with.
![Screenshot_20220108_012401](https://user-images.githubusercontent.com/9752483/148634216-a69db77c-6e94-483d-9fa6-62e403ac78d6.png)

#### Steps to reproduce the behaviour

1. Setup the windows 11 VM with `./quickget windows 11`
2. Run the VM with `./quickemu --vm windows-11.conf`
3. Set the language to English (United States), and install the rest as usual.
4. On the boot into Windows 11, the first page should prompt for a work login

#### Quickemu output
```
$ ./quickemu --version
3.11

$ ./quickget --version
Quickemu Version: 3.11

```

#### Linux Distribution & Kernel

```
$ lsb_release --all
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 35 (Thirty Five)
Release:        35
Codename:       ThirtyFive
$ uname -a
Linux SIRAF 5.15.12-200.fc35.x86_64 #1 SMP Wed Dec 29 15:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by jaylittle** [comment] 2022-01-08 12:37
So for starters, I experienced this very same issue myself yesterday.

Secondly, I spent some time messing with the unattend XML file being generated via quickget thinking I could fix this.  I was not able to resolve this issue however with any of the following workarounds:

1. Using my own ISO
2. Removing the Product Key from Unattend XML file (which honestly needs to be done anyway as this allows the user to either provide their own product key or select the edition of Windows 11 they want to install)
3. Removing OEM information from the Unattend XML file

I honestly have no idea why the setup is trying to associate the Windows 11 install to that enterprise org.  My best guess at this point is that maybe its a bug involving the EFI variables that are generated and one of those is somehow triggering some pre-existing logic in the Windows setup routine?

/shrug

**Comment by dist0rt3d** [comment] 2022-01-09 02:48
This worked for me:

- Close the setup window when it prompts for the organization login.
- Disconnect the host machine from the internet.
- Launch the Windows 11 VM again.

That should allow you to bypass the organization login and create your account.  Maybe keeping the product key in the autounattend.xml is the only way actually complete the install unattended?

**Comment by philclifford** [comment] 2022-01-09 22:37
Apparent re-appearance of #115 saga.

**Comment by aathif394** [comment] 2022-01-10 05:37
The solution given by @dist0rt3d works. I can confirm.

**Comment by flexiondotorg** [comment] 2022-02-19 15:37
Windows 11 will soon (or does now) require a Microsoft Account. See this article:

  * https://www.theverge.com/2022/2/18/22940517/windows-11-pro-require-microsoft-account-internet-connection

That said, we do need to solve the issue where "*random*" SIs are being elected for the online account authentication.

**Comment by flexiondotorg** [comment] 2022-02-21 05:20
Fixed via https://github.com/quickemu-project/quickemu/commit/0d6cd87494e3ffe71039163837d87341f694506e

  * You will need to run `quickget/quickemu` **from git** (until the next release is out)
  * Delete the `unattended.iso` in your VM directory
  * Run `quickget windows 11` to generate a new `unattended.iso`

**Comment by flexiondotorg** [comment] 2022-07-24 01:48
Looks like Microsoft has enforced organisation logins, which is causing the automated install to elect random orgs to auth against :sob:

**Closed** 2022-08-01 10:10 UTC
