### ISSUE TITLE
macOS Monterey doesn't work with multiple cores

### ISSUE THREAD

**Issue by Mischmaschine** [quickemu-project/quickemu#529] opened 2022-08-08 10:43 UTC
#### Expected behaviour

Start macOS Monterey with multiple core

#### Actual behaviour

The VM only starts if you the one core (cpu_cores="1")

#### Steps to reproduce the behaviour

Start the VM with more cores than one. It will instandly freeze on startup

```bash
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	        22.04
Codename:	jammy
Linux <Name> 5.15.0-43-generic
```

**Comment by alexdelorenzo** [comment] 2022-08-15 03:47
Running into what might be the same issue. When `cpu_cores` is set to anything but `1`, the VM will enter a boot loop after a disk is selected via the Mac's graphical bootloader. Setting the value to `1` allows me to successfully boot selected disks to the macOS desktop.

**Comment by alexdelorenzo** [comment] 2022-08-15 19:06
Looks like this is a duplicate of https://github.com/quickemu-project/quickemu/issues/438

**Comment by Mischmaschine** [comment] 2022-08-15 22:09
> @[alexdelorenzo](https://github.com/alexdelorenzo)
Sorry, didn't see the other issue which is already open! :grimacing:

**Closed** 2022-08-18 08:51 UTC
Labels: duplicate

**Comment by basarsubasi** [comment] 2024-12-26 16:02
I'm having this exact  issue right now.

CPU: AMD Ryzen 5 5600H
OS: Arch Linux
