### ISSUE TITLE
Ubuntu bionic release error - Ubuntu 18.0.4.2 LTS

### ISSUE THREAD

**Issue by stevenanthonyrevo** [quickemu-project/quickemu#266] opened 2021-12-06 19:30 UTC
#### Expected behaviour

Describe your expected behaviour.

Attempted to Add Quickemu repository and install on Linux ubuntu 18.0.4 

#### Actual behaviour

An error occurred while adding the repository. See the message below. 

```
The repository 'http://paa.launchpad.net/flexiondotorg/quickemu/ubuntu bionic Release' does not have a Release file.
```

#### Steps to reproduce the behaviour

```
sudo add-apt-repository ppa:flexiondotorg/quickemu
```

**Comment by daPhipz** [comment] 2021-12-06 19:58
Just to make sure - please check that you actually typed in this command:

```
sudo add-apt-repository ppa:flexiondotorg/quickemu
```

The error message suggests that you may have made a typo and typed `paa` instead of `ppa`, which would explain the failure.

**Comment by flexiondotorg** [comment] 2021-12-06 23:58
Duplicate of #172

**Closed by flexiondotorg** 2021-12-06 23:58 UTC
