### ISSUE TITLE
bug: quickemu returns errno 1 after successful launch

### ISSUE THREAD

**Issue by popey** [quickemu-project/quickemu#1170] opened 2024-05-07 21:28 UTC
#### Expected behaviour

If I successfully use quickget then quickemu to download and launch an emulator, I expect a return code 0.

#### Actual behaviour

I get a returncode 1

#### Steps to reproduce the behaviour

`quickget ubuntu 24.04`

`./ubuntu-20.04.conf`

#### Quickemu output

Run `quickemu` or `quickget` and paste the output here.

```bash
$ ./ubuntu-24.04.conf 
Quickemu 4.9.1 using /usr/bin/qemu-system-x86_64 v8.2.2
 - Host:     Ubuntu 24.04 LTS running Linux 6.8 (ziggy)
 - CPU:       AMD Ryzen 7 PRO 6860Z with Radeon Graphics
 - CPU VM:   1 Socket(s), 4 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (Linux), OVMF (/usr/share/OVMF/OVMF_CODE_4M.fd), SecureBoot (off).
 - Disk:     ubuntu-24.04/disk.qcow2 (16G)
             Looks unused, booting from ubuntu-24.04/ubuntu-24.04-desktop-amd64.iso
 - Boot ISO: ubuntu-24.04/ubuntu-24.04-desktop-amd64.iso
 - Display:  SDL, virtio-vga-gl, GL (on), VirGL (on)
 - Sound:    intel-hda
 - ssh:      On host:  ssh user@localhost -p 22220
 - WebDAV:   On guest: dav://localhost:9843/
 - 9P:       On guest: sudo mount -t 9p -o trans=virtio,version=9p2000.L,msize=104857600 Public-alan ~/alan
 - smbd:     On guest: smb://10.0.2.4/qemu
 - Network:  User (virtio-net)
 - Monitor:  On host:  nc -U "ubuntu-24.04/ubuntu-24.04-monitor.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:ubuntu-24.04/ubuntu-24.04-monitor.socket
 - Serial:   On host:  nc -U "ubuntu-24.04/ubuntu-24.04-serial.socket"
             or     :  socat -,echo=0,icanon=0 unix-connect:ubuntu-24.04/ubuntu-24.04-serial.socket
 - Process:  Starting ./ubuntu-24.04.conf as ubuntu-24.04 (64787)
$  echo $?
1
```
`

#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
$ lsb_release --all
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble

$ uname -a
Linux ziggy 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by popey** [comment] 2024-05-07 21:32
If I `set -x` at the top of `/usr/bin/quickemu` it appears to end here:

```
++ cat ubuntu-24.04/ubuntu-24.04.pid
+ echo ' - Process:  Starting ./ubuntu-24.04.conf as ubuntu-24.04 (69867)'
 - Process:  Starting ./ubuntu-24.04.conf as ubuntu-24.04 (69867)
+ '[' -n ubuntu-24.04/ubuntu-24.04-desktop-amd64.iso ']'
+ '[' linux == windows ']'
+ start_viewer
+ errno=0
+ '[' spicy '!=' none ']'
+ '[' sdl == spice ']'
+ '[' -n '' ']'

```

It looks like the [start_viewer](https://github.com/quickemu-project/quickemu/blob/master/quickemu#L1326) function is causing this. 

This is only one occurrence of `exit 1` around the code. I am wondering if this could be cleaned up so genuine failures exit correctly.

**Comment by lj3954** [comment] 2024-05-07 22:56
Duplicate of #531. Fixed in https://github.com/quickemu-project/quickemu/commit/dc81b8c2b3d12eb516f0b590bae798b8e5f1e1fa

**Closed** 2024-05-08 00:13 UTC
